# Generated by Django 4.0.1 on 2022-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_friend_delete_publicchatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
